comments:
  lineComment: "#"
brackets:
  - - "["
    - "]"
  - - "{"
    - "}"
  - - "("
    - ")"
  - - "$("
    - ")"
autoClosingPairs:
  - - "["
    - "]"
  - - "{"
    - "}"
  - - "("
    - ")"
  - - "\""
    - "\""
  - open: "$("
    close: ")"
  - open: "L\""
    close: "\""
folding:
  markers:
    start: "^\\s*\\[([^\\]]+)\\]|^\\s*!(?i)(if|ifdef|ifndef)\\b"
    end: "^\\s*!(?i)(endif)\\b"
